# Generated by Django 4.1.7 on 2024-07-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_user_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
